### ISSUE TITLE
Tacos with pineapple

### ISSUE THREAD

**Issue by ecaas** [ziu1986/forking-workflow-exercise#1]
I want to add a taco recipe that contains pineapple chunks.
Would love to get some feedback on this.

**Comment by zhanghuiying2319** [comment]
Sounds good

**Comment by ziu1986** [comment]
It sounds refreshing and lovely!

**Comment by magnudry** [comment]
Pineapple is delicious!

**Comment by alpsjur** [comment]
Sounds good!
